[theme]
primaryColor="#08c3d9"
backgroundColor="#058efa"
secondaryBackgroundColor="#0897d9"
textColor="#ffffff"
font="monospace"

[server]
enableStaticServing = false

[client]
showSidebarNavigation = false


