[theme]
primaryColor="#1282A2"
backgroundColor="#034078"
secondaryBackgroundColor="#001F54"
textColor="#ffffff"
font="sans serif"

[server]
enableStaticServing = false

[client]
showSidebarNavigation = false


